name: chitalka
description: "A new Flutter project."

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.0.0
  xml: ^6.5.0
  file_picker: ^10.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.0
  shared_preferences: ^2.1.1
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  archive: ^3.1.0
  string_similarity: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.0
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/dicts/rus-eng/rus-eng.dict
    - assets/dicts/rus-eng/rus-eng.index
    - assets/dicts/eng-rus/eng-rus.dict
    - assets/dicts/eng-rus/eng-rus.index
    - assets/dicts/rus-ita/rus-ita.dict
    - assets/dicts/rus-ita/rus-ita.index
    - assets/dicts/ita-rus/ita-rus.dict
    - assets/dicts/ita-rus/ita-rus.index
    - assets/dicts/ita-eng/ita-eng.dict
    - assets/dicts/ita-eng/ita-eng.index
    - assets/dicts/eng-ita/eng-ita.dict
    - assets/dicts/eng-ita/eng-ita.index
